name: George Stefanis
markdown: redcarpet
highlighter: true
timezone: Greenwich
paginate: 10
paginate_path: "/page:num/"
url:  http://www.georgestefanis.com
description: Thoughts and experiments
gems: [jekyll-gist, jekyll-paginate]
keep_files: ['.well-known/acme-challenge']
