name: George Stefanis
markdown: redcarpet
highlighter: true
timezone: Greenwich
paginate: 10
future: true
paginate_path: "/page:num/"
url:  https://www.georgestefanis.com
description: Thoughts and experiments
gems: [jekyll-gist, jekyll-paginate]
keep_files: ['.well-known/acme-challenge']
sass:
  style: compressed
